version: "3.6" #版本
services:
  go-tcp-server:
    image: centos-go
    container_name: go-tcp-server
    ports:
      - "8300:8300"
      - "3000:3000"
    volumes:
      - /www/study/golang/src/d5/tcp/server:/go/src/tcp/server
    working_dir: /go/src
    networks:
      go:
        ipv4_address: 192.168.5.20
    command: top -b
  go-tcp-client:
    image: centos-go
    container_name: go-tcp-client
    volumes:
      - /www/study/golang/src/d5/tcp/client:/go/src/tcp/client
    working_dir: /go/src
    networks:
      go: # 引用下面的桥接网络
        ipv4_address: 192.168.5.30
    command: top -b
networks:
  go: #使用已经存在网络
    external:
      name: go
#  go: #网络名：目录_go
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.5.0/24